# Generated by Django 5.0.4 on 2026-03-23 11:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('resolution', models.CharField(choices=[('1920x1080', 'Full HD (1920×1080)'), ('3840x2160', '4K UHD (3840×2160)'), ('1080x1920', 'Portrait HD (1080×1920)'), ('1080x1080', 'Square (1080×1080)')], default='1920x1080', max_length=20)),
                ('width_cm', models.PositiveIntegerField(help_text='Physical width in centimetres')),
                ('height_cm', models.PositiveIntegerField(help_text='Physical height in centimetres')),
                ('price_per_slot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='boards/thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'boards_board',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BoardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='boards/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='boards.board')),
            ],
            options={
                'db_table': 'boards_board_image',
                'ordering': ['order'],
            },
        ),
    ]
