# Generated by Django 5.0.4 on 2026-03-23 11:30

import apps.ads.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.ads.models.ad_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'webm'])])),
                ('ad_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('duration_seconds', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ad', to='bookings.booking')),
            ],
            options={
                'db_table': 'ads_ad',
                'ordering': ['-created_at'],
            },
        ),
    ]
